name: Publish Python 🐍 distributions 📦 to Test PyPI

on: workflow_dispatch

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to Test PyPI
    runs-on: ubuntu-latest
    environment: testpypi
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Rename package for test
      uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-file: './setup.py'
        _output-file: './setup.py'
        gitrepo: 'gitrepo-test'
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
